### ISSUE TITLE
fltk-form and fl2rust interaction

### ISSUE THREAD

**Issue by 1sra3l** [fltk-rs/fl2rust#10]
Hi,
I am struggling with figuring out the correct way to update a group created by fltk-form in the UI created via FLUID + fl2rust.
I have tried
```rs
let my_struct = MyStruct::default(); // also used manual creation, serde from toml
let fluid_group = ui.group_in_the_file; // .clone(); or even Group::default().whatever....
let mut fltkform_group = my_struct::generate(); // works
fluid_group.end(); //works
ui.group_in_the_file = fluid_group;//.clone();  neither work :(
ui.group_in_the_file.redraw();//nothing and ui.win.redraw(); nothing as well
```
but could only get this working, somewhat:
```rs
let my_struct = MyStruct::default(); // also used manual, serde from toml
let new_group = Group::default(); //.whatever....
let mut fltkform_group = my_struct::generate(); // works
new_group.end(); //works
ui.group_in_the_file.add(&new_group); // works but `.clear()` seems to crash it.
ui.win.redraw();
```
Mostly I want to change the values and read the values.  There is no way to change them from the API, as far as I could tell.
I think ultimately, clear documentation of interactions between the various parts of your amazing fltk Rust universe could be helpful.

I guess I  could also read all the code you have written and learn it that way :smile_cat:

**Comment by MoAlyousef** [comment]
The generated code `end()`s every GroupExt widget. I can't try this now, but can you try:
```rust
let my_struct = MyStruct::default();
ui.group_in_the_file.begin();
let mut fltkform_group = my_struct::generate();
ui.group_in_the_file.end();
```
Calling clear() basically deletes any created widgets, the crash is probably an assert that the called widget is no longer available.
Currently you can get the values using get_prop and get_props. I can provide a set_prop() method in the fltk-form crate for setting values.

**Comment by 1sra3l** [comment]
@MoAlyousef works perfectly!  I never used it in that way in the C++ , this makes complete sense as to why it should work this way, and does.  Thanks so much, this is another thing to specifically highlight in the docs!  If this could be in the `fltk::group`  (group.rs?) page it would be clear it applied to all the other variants, though it might be good to put it in the GroupExt trait (prelude.rs?) as well so both places have the documentation.

Are the docs hand-written or generated from something somewhere else?

**Comment by MoAlyousef** [comment]
Most of the docs are hand-written, some are copy-pasted from FLTK :P
But the idea of adding docs to the traits themselves sounds good.

**Comment by 1sra3l** [comment]
Ok so I can PR something in prelude and group and it wont be written over by a macro somewhere!  Thanks, I noticed random code from the repo showing up now in the docs, that really is a cool feature!  How did you enable that?

**Comment by MoAlyousef** [comment]
Yes. You can enable it by adding to your Cargo.toml:

```toml
[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
```

**Comment by 1sra3l** [comment]
Thanks, I think the feature is really cool!  I will check it out!
