### ISSUE TITLE
hide as label causes widget to hide

### ISSUE THREAD

**Issue by 1sra3l** [fltk-rs/fl2rust#13]
I made something with the label "hide" and it hid the widget. According to the [src](https://github.com/fltk-rs/fl2rust/blob/main/src/reserved.rs#L48) it is a reserved word.

I was able to work around the issue by using "[SPACE]hide"

Would changing the reserved word to "hide()" work still?

**Comment by MoAlyousef** [comment]
I've pushed a fix and published a new release
