### ISSUE TITLE
fl2rust does not embeds images (just stores the file path)

### ISSUE THREAD

**Issue by diegoefe** [fltk-rs/fl2rust#30]
In fuild's original version (c++) when you select a file for a button the resulting .cpp/cxx file embeds the binary representation of the file.
It will be great if fl2rust could do the same. Actuallly it stores the path of the file and it's not usable, IMHO
![Screenshot from 2024-09-12 09-59-20](https://github.com/user-attachments/assets/5a1f08e6-89de-4928-832d-a23f912248ef)
![Screenshot from 2024-09-12 10-01-45](https://github.com/user-attachments/assets/db8a10bf-82f2-4fe7-aecf-8c74d97e6547)

**Comment by MoAlyousef** [comment]
I'll try to make it embed the images binary content.

**Comment by diegoefe** [comment]
Excellent, thanks
