### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by 1sra3l** [fltk-rs/fl2rust#9]
Hi I am trying to understand fl2rust returning `Function` as `pub fn`
I think [here](https://github.com/fltk-rs/fl2rust/blob/main/src/parser.rs#L87) is where things really happen
```rs
                "Function" => {
                    let return_type = false;
                    if words.len() > 2 {
                        for i in 0..words.len() {
                            let name = utils::unbracket(&words[1]).to_string();
                            if words[i] == "return_type" {
                                // does this not just work?
                                ast.ident = format!(
                                    "{} -> {}",
                                    name,
                                    utils::unbracket(&words[i + 1]).to_string()
                                );
                                ast.typ = TokenType::Function;
                                break;
                            } else {
                                ast.ident = name.clone();
                                ast.typ = TokenType::Function;
                            }
                        }
                        parent.push(format!("Function {}", ast.ident.clone()));
                    }
                }
```
Is is commented out because it does not work, or because of [this](https://github.com/fltk-rs/fl2rust/blob/14d19f28bb6439601b2a37881e0d7b85b279ac6e/src/gen.rs#L57)
specifically:
```rs
if !elem.ident.contains("-> Self") {
//...
}
```
Could this be changed to:
```rs
if !elem.ident.contains("->") {
//...
}
```
To support writing functions in FLUID?

**Comment by MoAlyousef** [comment]
Hello
Currently Function's assume they're a constructor, and would generate a struct, that's why they return Self. For the moment, standalone functions and struct methods aren't supported (ie it would require much more code changes).

**Comment by 1sra3l** [comment]
Ok thanks! If I get really interested in this at some point I may really look through the code and re-open this if I have anything useful to add
